# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:
    providers:
        in_memory:
            memory:
                users:
                    ryan:
                        password: $2y$12$SLIGlFtf9bzezqXz.YuoY.z5PfLDeSaK.cwFLP55AU34KxTYQc4jK
                        roles: 'ROLE_USER'
                    admin:
                        password: $2y$12$zjMLZ9Zz3mqO4bIpL.teUugxXOm9QOIi12CVhmgODCNvGd78J5gKm
                        roles: 'ROLE_ADMIN'

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
            # activate different ways to authenticate

            http_basic: ~
            # http://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate

            # form_login: ~
            # http://symfony.com/doc/current/cookbook/security/form_login_setup.htmls

    access_control:
            - { path: ^/(.+), roles: [ROLE_ADMIN, ROLE_USER] }

    encoders:
            Symfony\Component\Security\Core\User\User:
                algorithm: bcrypt
                cost: 12
